// components/usermanagement/pendinginvitation/PendingInvitationDetails.jsx

import {
  ShieldCheck,
  TrendingUp,
  Mail,
  MessageSquare,
  Clock3,
  Edit3,
  ChevronRight,
  Eye,
  PlusCircle,
} from 'lucide-react'

export default function PendingInvitationDetails() {
  return (
    <div className="mt-6 grid grid-cols-1 gap-5 xl:grid-cols-[1.45fr_0.7fr]">
      <div className="space-y-5">
        <div className="rounded-[26px] border border-[#EEF1EF] bg-white p-8 shadow-sm">
          <div className="flex items-center gap-2">
            <ShieldCheck className="h-5 w-5 text-brand-primary" />

            <h2 className="text-[22px] font-semibold text-[#202939]">
              User Access Summary
            </h2>
          </div>

          <div className="mt-9 grid grid-cols-1 gap-8 md:grid-cols-2">
            <div>
              <p className="text-[12px] uppercase text-[#6B7280]">
                Assigned Role
              </p>

              <p className="mt-2 text-[15px] font-semibold text-brand-primary">
                State Admin
              </p>
            </div>

            <div>
              <p className="text-[12px] uppercase text-[#6B7280]">
                Reporting Manager
              </p>

              <p className="mt-2 text-[15px] font-semibold text-[#202939]">
                Marcus Thorne
              </p>
            </div>

            <div>
              <p className="text-[12px] uppercase text-[#6B7280]">
                Assigned Regions
              </p>

              <p className="mt-2 text-[15px] text-[#374151]">
                Maharashtra / Pune District
              </p>
            </div>

            <div>
              <p className="text-[12px] uppercase text-[#6B7280]">
                Access Visibility
              </p>

              <p className="mt-2 text-[15px] leading-6 text-[#374151]">
                Restricted Access (State-level hierarchy)
              </p>
            </div>
          </div>

          <div className="mt-8">
            <p className="text-[12px] uppercase text-[#6B7280]">
              Enabled Modules
            </p>

            <div className="mt-4 flex flex-wrap gap-3">
              {['Farmers', 'Activities', 'Tasks', 'Reports'].map((item) => (
                <span
                  key={item}
                  className="rounded-full bg-[#EEF2F0] px-4 py-1.5 text-[12px] font-semibold text-[#202939]"
                >
                  {item}
                </span>
              ))}
            </div>
          </div>
        </div>

        <div className="rounded-[26px] border border-[#EEF1EF] bg-white p-8 shadow-sm">
          <div className="flex items-center gap-2">
            <Clock3 className="h-5 w-5 text-brand-primary" />

            <h2 className="text-[22px] font-semibold text-[#202939]">
              Activity Timeline
            </h2>
          </div>

          <div className="mt-9 space-y-6 border-l border-[#C9D1CD] pl-6">
            {[
              {
                title: 'Invitation Opened',
                desc: 'The invitation link was accessed from Chrome (Android 13).',
                time: '2 mins ago',
                icon: Eye,
                active: true,
              },
              {
                title: 'SMS Sent',
                desc: 'Onboarding instructions sent via SMS to +91 98230 44556.',
                time: 'Oct 24, 14:35',
                icon: MessageSquare,
              },
              {
                title: 'Email Delivered',
                desc: 'Primary invitation email successfully delivered to recipient inbox.',
                time: 'Oct 24, 14:33',
                icon: Mail,
              },
              {
                title: 'Invitation Created',
                desc: 'Invitation generated by Admin Alex Sterling.',
                time: 'Oct 24, 14:32',
                icon: PlusCircle,
              },
            ].map((item) => {
              const Icon = item.icon

              return (
                <div key={item.title} className="relative">
                  <div
                    className={`absolute -left-[34px] top-0 flex h-5 w-5 items-center justify-center rounded-full ${
                      item.active ? 'bg-brand-primary' : 'bg-[#D9E5E1]'
                    }`}
                  >
                    <Icon className="h-3 w-3 text-white" />
                  </div>

                  <div className="flex justify-between gap-4">
                    <div>
                      <h3 className="text-[15px] font-semibold text-[#202939]">
                        {item.title}
                      </h3>

                      <p className="mt-1 text-[12px] leading-5 text-[#4B5563]">
                        {item.desc}
                      </p>
                    </div>

                    <p className="shrink-0 text-[12px] font-medium text-brand-primary">
                      {item.time}
                    </p>
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      </div>

      <div className="space-y-5">
        <div className="rounded-[22px] border border-[#EEF1EF] bg-white p-5 shadow-sm">
          <h3 className="text-[15px] font-semibold text-[#202939]">
            Security & Compliance
          </h3>

          <div className="mt-4 space-y-4 text-[12px]">
            <div className="flex justify-between">
              <span className="text-[#4B5563]">Invitation Expiry</span>
              <span className="font-semibold">Oct 26, 2023</span>
            </div>

            <div className="flex justify-between">
              <span className="text-[#4B5563]">Identity Verification</span>
              <span className="rounded-full bg-[#FEF3C7] px-3 py-1 text-[10px] font-semibold text-[#B45309]">
                PENDING
              </span>
            </div>

            <div className="flex justify-between">
              <span className="text-[#4B5563]">Device Security</span>
              <span className="font-semibold">Awaiting Setup</span>
            </div>
          </div>
        </div>

        <div className="rounded-[22px] border border-[#EEF1EF] bg-white p-5 shadow-sm">
          <div className="flex items-center gap-2">
            <TrendingUp className="h-4 w-4 text-brand-primary" />

            <h3 className="text-[15px] font-semibold text-[#202939]">
              Operational Insights
            </h3>
          </div>

          <div className="mt-5 space-y-4 text-[12px]">
            <div className="flex justify-between">
              <span>Days Pending</span>
              <span className="text-[18px] font-semibold text-brand-primary">
                0.5
              </span>
            </div>

            <div className="flex justify-between">
              <span>Activity Level</span>
              <span className="rounded-full bg-[#DCFCE7] px-3 py-1 text-[10px] font-semibold text-[#16A34A]">
                HIGH
              </span>
            </div>

            <div>
              <div className="flex justify-between">
                <span>Onboarding Completion</span>
                <span>40%</span>
              </div>

              <div className="mt-2 h-2 rounded-full bg-[#E5E7EB]">
                <div className="h-full w-[40%] rounded-full bg-brand-primary" />
              </div>
            </div>
          </div>
        </div>

        <p className="text-[13px] uppercase text-[#4B5563]">
          Quick Actions
        </p>

        {[
          {
            label: 'Resend Email',
            icon: Mail,
          },
          {
            label: 'Resend SMS',
            icon: MessageSquare,
          },
          {
            label: 'Extend Validity',
            icon: Clock3,
          },
          {
            label: 'Edit Access',
            icon: Edit3,
          },
        ].map((item) => {
          const Icon = item.icon

          return (
            <button
              key={item.label}
              className="flex w-full items-center justify-between rounded-2xl bg-white px-5 py-4 shadow-sm"
            >
              <div className="flex items-center gap-3">
                <div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#EEF2F0]">
                  <Icon className="h-4 w-4 text-brand-primary" />
                </div>

                <span className="text-[14px] font-semibold text-[#202939]">
                  {item.label}
                </span>
              </div>

              <ChevronRight className="h-4 w-4" />
            </button>
          )
        })}
      </div>
    </div>
  )
}