

import clsx from 'clsx'
import {
  FileText,
  Tractor,
  BrainCircuit,
  Download,
  Eye,
  Share2,
  ChevronLeft,
  ChevronRight,
} from 'lucide-react'

const reports = [
  {
    name: 'Monthly Financial Audit - Q3',
    type: 'Financial',
    generatedBy: 'Alex Rivera',
    initials: 'AR',
    date: 'Oct 24, 2023',
    format: 'PDF',
    status: 'Ready',
    icon: 'file',
  },
  {
    name: 'Agent Productivity Matrix',
    type: 'Operational',
    generatedBy: 'Sarah Kim',
    initials: 'SK',
    date: 'Oct 22, 2023',
    format: 'XLSX',
    status: 'Ready',
    icon: 'tractor',
  },
  {
    name: 'Advisory Reach Analysis',
    type: 'Impact',
    generatedBy: 'Alex Rivera',
    initials: 'AR',
    date: 'Oct 20, 2023',
    format: 'PDF',
    status: 'Generating',
    icon: 'brain',
  },
]

const icons = {
  file: FileText,
  tractor: Tractor,
  brain: BrainCircuit,
}

export default function RecentReportsTable() {
  return (
   <div className="mt-6 rounded-[28px] bg-white p-5 shadow-[0_16px_40px_rgba(0,0,0,0.07)]">
  <div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between">
    <h2 className="text-[20px] font-semibold text-brand-primary">
      Recently Generated Reports
    </h2>

    <div className="flex items-center overflow-hidden rounded-xl border border-[#D7DDDA]">
      <button className="bg-[#DDE4E1] px-6 py-2 text-[13px] font-semibold text-[#2B2B2B]">
        Active
      </button>

      <button className="bg-white px-6 py-2 text-[13px] font-medium text-[#5B5B5B]">
        Archived
      </button>
    </div>
  </div>

  <div className="mt-5 overflow-x-auto">
    <table className="min-w-full border-separate border-spacing-y-0">
      <thead>
        <tr className="bg-[#F4F6F5] text-left">
          <th className="rounded-l-2xl px-7 py-5 text-[11px] font-semibold uppercase tracking-wide text-[#4B5563]">
            Report Name
          </th>

          <th className="px-5 py-5 text-[11px] font-semibold uppercase tracking-wide text-[#4B5563]">
            Type
          </th>

          <th className="px-5 py-5 text-[11px] font-semibold uppercase tracking-wide text-[#4B5563]">
            Generated By
          </th>

          <th className="px-5 py-5 text-[11px] font-semibold uppercase tracking-wide text-[#4B5563]">
            Date
          </th>

          <th className="px-5 py-5 text-[11px] font-semibold uppercase tracking-wide text-[#4B5563]">
            Format
          </th>

          <th className="px-5 py-5 text-[11px] font-semibold uppercase tracking-wide text-[#4B5563]">
            Status
          </th>

          <th className="rounded-r-2xl px-5 py-5 text-[11px] font-semibold uppercase tracking-wide text-[#4B5563]">
            Actions
          </th>
        </tr>
      </thead>

      <tbody>
        {reports.map((report, index) => {
          const Icon = icons[report.icon]

          return (
            <tr
              key={index}
              className="border-b border-[#EEF1EF]"
            >
              <td className="px-7 py-7">
                <div className="flex items-center gap-3">
                  <div className="text-brand-primary">
                    <Icon className="h-5 w-5" />
                  </div>

                  <span className="text-[15px] font-semibold text-[#1F2937]">
                    {report.name}
                  </span>
                </div>
              </td>

              <td className="px-5 py-7 text-[14px] text-[#374151]">
                {report.type}
              </td>

              <td className="px-5 py-7">
                <div className="flex items-center gap-2.5">
                  <div className="flex h-7 w-7 items-center justify-center rounded-full bg-[#D9E4E1] text-[11px] font-bold text-brand-primary">
                    {report.initials}
                  </div>

                  <span className="text-[14px] text-[#374151]">
                    {report.generatedBy}
                  </span>
                </div>
              </td>

              <td className="px-5 py-7 text-[14px] text-[#374151]">
                {report.date}
              </td>

              <td className="px-5 py-7">
                <span
                  className={clsx(
                    'rounded-md px-3 py-1 text-[11px] font-bold',
                    report.format === 'PDF'
                      ? 'bg-[#FCECEC] text-[#DC2626]'
                      : 'bg-[#E8F5EC] text-[#15803D]'
                  )}
                >
                  {report.format}
                </span>
              </td>

              <td className="px-5 py-7">
                <span
                  className={clsx(
                    'inline-flex items-center gap-2 rounded-full px-3 py-1 text-[12px] font-medium',
                    report.status === 'Ready'
                      ? 'bg-[#DCFCE7] text-[#15803D]'
                      : 'bg-[#FEF3C7] text-[#B45309]'
                  )}
                >
                  <div
                    className={clsx(
                      'h-2 w-2 rounded-full',
                      report.status === 'Ready'
                        ? 'bg-[#16A34A]'
                        : 'bg-[#D97706]'
                    )}
                  />

                  {report.status}
                </span>
              </td>

              <td className="px-5 py-7">
                <div className="flex items-center gap-4 text-[#111827]">
                  <button>
                    <Download className="h-4.5 w-4.5" />
                  </button>

                  <button>
                    <Eye className="h-4.5 w-4.5" />
                  </button>

                  <button>
                    <Share2 className="h-4.5 w-4.5" />
                  </button>
                </div>
              </td>
            </tr>
          )
        })}
      </tbody>
    </table>
  </div>

  <div className="mt-7 flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between">
    <p className="text-[14px] text-[#4B5563]">
      Showing 3 of 124 reports
    </p>

    <div className="flex items-center gap-2">
      <button className="flex h-10 w-10 items-center justify-center rounded-xl border border-[#D7DDDA] bg-white">
        <ChevronLeft className="h-4 w-4" />
      </button>

      <button className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-primary text-[13px] font-semibold text-white">
        1
      </button>

      <button className="flex h-10 w-10 items-center justify-center rounded-xl border border-[#D7DDDA] bg-white text-[13px] font-semibold text-[#4B5563]">
        2
      </button>

      <button className="flex h-10 w-10 items-center justify-center rounded-xl border border-[#D7DDDA] bg-white text-[13px] font-semibold text-[#4B5563]">
        3
      </button>

      <button className="flex h-10 w-10 items-center justify-center rounded-xl border border-[#D7DDDA] bg-white">
        <ChevronRight className="h-4 w-4" />
      </button>
    </div>
  </div>
</div>
  )
}